### ISSUE TITLE
Results for TRADES

### ISSUE THREAD

**Issue by csdongxian** [Line290/FeatureAttack#1]
Thanks for your code~ I have some questions:
1) I notice that a stronger Feature Attack is used for TRADES, could you tell us the reason ? 
2) Besides, can you add the result for TRADES under FeatureAttack-20-1-8-100 ? It is important to compare different methods in fairness.

**Comment by Line290** [comment]
Hi @csdongxian ,

Sorry for later replying. I'm glad you are interested in my work. 
1. To my knowledge, Madry's PGD adversarial training and TRADES are very strong defenses. I just want to know whether Feature Attack can beat TRADES. Also, I want to check whether TRADES is the same as Label-smoothing. Both in Bilateral Adversarial Training and Feature Scattering, Label-smoothing plays an important role to gain robustness.

2. Sorry, I wasn't doing that. For the white-box setting, I think 20 steps or 50 steps is doesn't matter. To evaluate the robustness of a new defense, we are always going to attack at least 1000 steps.

**Comment by csdongxian** [comment]
Thanks for your reply :)
